---
- hosts: myBastion
  tasks:

  - name: "PREP-SSHKEYS: file/directory .ssh permissions"
    file:
      path: ~{{ g_studentName }}/.ssh
      mode: "0700"
      owner: "{{ g_studentName }}"
      group: "{{ g_studentName }}"
      state: directory

  - name: "PREP-SSHKEYS: known_hosts {{ g_studentName }} file permissions"
    file:
      path: "~{{ g_studentName }}/.ssh/known_hosts"
      mode: "0700"
      owner: "{{ g_studentName }}"
      group: "{{ g_studentName }}"
      state: touch

  - name: "PREP-SSHKEYS: openssh_keypair {{ g_studentName }} create"
    openssh_keypair:
      path:  ~{{ g_studentName }}/.ssh/id_rsa
      owner: "{{ g_studentName }}"
      group: "{{ g_studentName }}"

  - name: "PREP-SSHKEYS: clean out local ssh keys"
    vars:
      p_file: "~{{ g_studentName }}/.ssh/known_hosts"
    shell:
      cmd: |
        ssh-keygen -f {{ p_file }} -R {{ hostvars[item]['inventory_hostname_short'] }}
        ssh-keygen -f {{ p_file }} -R {{ hostvars[item]['inventory_hostname_short'] }}.{{ ansible_domain }}
    loop: "{{ [ groups['myBastion'], groups['myNodes'] ]  | flatten(1) }}"
    ignore_errors: yes

  - name: "PREP-SSHKEYS: add ssh keys for nodes"
    vars:
      p_file: "~{{ g_studentName }}/.ssh/known_hosts"
    shell:
      cmd: |
        ssh-keyscan {{ hostvars[item]['inventory_hostname_short'] }} >> {{ p_file }}
        ssh-keyscan {{ hostvars[item]['inventory_hostname_short'] }}.{{ ansible_domain }} >> {{ p_file }}
    loop: "{{ [ groups['myBastion'], groups['myNodes'] ]  | flatten(1) }}"
    ignore_errors: yes




- hosts: nodes
  tasks:

  - name: "PREP-SSHKEYS: file/directory .ssh permissions"
    file:
      path: ~{{ g_studentName }}/.ssh
      mode: "0700"
      owner: "{{ g_studentName }}"
      group: "{{ g_studentName }}"
      state: directory

  - name: "PREP-SSHKEYS: authorized_key deployment"
    authorized_key:
      user: "{{ g_studentName }}"
      state: present
      key: "{{ lookup('file','~{{ g_studentName }}/.ssh/id_rsa.pub' ) }}"

